[project]
name = "dsp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cudf-cu12>=24.12.0",
    "matplotlib>=3.10.0",
    "python3-12-tk",
    "scipy>=1.15.1",
]
